# Compiler settings
FC = gfortran
# -J tells gfortran where to store and look for compiled .mod files
FFLAGS = -O2 -Wall -J ../build
#FFLAGS = -O2 -Wall -fcheck=bounds -J ../build

# Target executable
PROG = obs_rinex3_prog3
MAIN_SRC = obs_rinex3_prog3.f90

# Directory paths relative to the 'examples' folder
SRC_DIR = ../rinexer_src
BUILD_DIR = ../build

# The single merged module object file
MOD_OBJECT = $(BUILD_DIR)/obs_rinex3_mod.o

# Main target - linking the final executable
$(PROG): $(MOD_OBJECT) $(MAIN_SRC)
	$(FC) $(FFLAGS) $(MOD_OBJECT) $(MAIN_SRC) -o $(PROG)

# Rule to compile the single merged module
$(MOD_OBJECT): $(SRC_DIR)/obs_rinex3_mod.f90
	@mkdir -p $(BUILD_DIR)
	$(FC) $(FFLAGS) -c $(SRC_DIR)/obs_rinex3_mod.f90 -o $(MOD_OBJECT)

# Clean rule - removes the build folder and the executable from 'examples'
clean:
	rm -rf $(BUILD_DIR)
	rm -f $(PROG)